# Generated by Django 4.1.1 on 2022-09-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotapp', '0004_drink_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='drink_tag',
            field=models.CharField(blank=True, choices=[('MOJITIO', 'Mojito'), ('SHAKES_ICEBLENDS', 'Shakes & Ice Blends'), ('JUGO', 'Jugo'), ('HOTDRINKS', 'Hot Drinks')], max_length=50, null=True),
        ),
    ]
